# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey('auth.User'),
            preserve_default=False,
        ),
    ]
